import { describe, expect, it } from 'vitest';
import { STARTER_JOB } from '../features/economy';
import { createInitialGameState } from './game-state';
import { evaluateDeliveryRewardBase, evaluateJobReward } from './effective-stats';
import { performRiskyDelivery, performStarterJob } from './perform-starter-job';
import { isManualJobReady, MANUAL_JOB_INTERVAL_MS, manualJobRemainingMs } from './manual-job-readiness';
import { simulateGameElapsed } from './simulate-game-elapsed';
import { CURRENT_SAVE_VERSION, SAVE_FORMAT, migrateToCurrentSave, parseSave, serializeSave } from './save-schema';
import { exportSaveCode, validateSaveCode } from './save-code';
import { performRebirth } from './rebirth';
import { rebirthState } from './test-fixtures/rebirth-state';

describe('Operations cadence — free standard clicker and shared special readiness', () => {
  function portfolio() { const state = createInitialGameState(); return { ...state, businesses: { ...state.businesses, owned: { 'business:dockside-detail': { level: 7 }, 'business:neon-laundry': { level: 10 }, 'business:afterdark-customs': { level: 1 } } } }; }
  it('keeps reward scaling and the fresh special slot', () => { const fresh = createInitialGameState(); expect(isManualJobReady(fresh.manualJobs)).toBe(true); expect(evaluateDeliveryRewardBase(fresh, 'manual')).toEqual({ ok: true, base: STARTER_JOB.reward }); const state = portfolio(); expect(evaluateDeliveryRewardBase(state, 'manual')).toEqual({ ok: true, base: '56200' }); expect(evaluateDeliveryRewardBase(state, 'dispatcher')).toEqual({ ok: true, base: '7025' }); expect(evaluateJobReward(state)).toMatchObject({ ok: true, base: '56200' }); });
  it('lets standard deliveries run repeatedly without consuming special readiness', () => { const fresh = createInitialGameState(); const one = performStarterJob(fresh); expect(one.ok).toBe(true); if (!one.ok) return; expect(one.state.manualJobs).toBeUndefined(); const two = performStarterJob(one.state); expect(two.ok).toBe(true); if (!two.ok) return; expect(two.state.manualJobs).toBeUndefined(); expect(two.state.progression.xp).toBe(20); expect(two.state.city.heat).toBe(2); });
  it('shares one cooldown between risky and discreet while standard stays available', () => { const risky = performRiskyDelivery(createInitialGameState()); expect(risky.ok).toBe(true); if (!risky.ok) return; expect(risky.state.manualJobs).toEqual({ elapsedMs: 0 }); expect(performRiskyDelivery(risky.state)).toMatchObject({ ok: false, error: 'manual-job-not-ready', remainingMs: MANUAL_JOB_INTERVAL_MS }); const standard = performStarterJob(risky.state); expect(standard.ok).toBe(true); if (!standard.ok) return; expect(standard.state.manualJobs).toEqual({ elapsedMs: 0 }); });
  it('restores only the special slot and never banks special actions', () => { const risky = performRiskyDelivery(createInitialGameState()); expect(risky.ok).toBe(true); if (!risky.ok) return; const almost = simulateGameElapsed(risky.state, MANUAL_JOB_INTERVAL_MS - 1); expect(almost.ok).toBe(true); if (!almost.ok) return; expect(manualJobRemainingMs(almost.state.manualJobs)).toBe(1); const ready = simulateGameElapsed(almost.state, 60_000); expect(ready.ok).toBe(true); if (!ready.ok) return; expect(ready.state.manualJobs).toBeUndefined(); });
  it('preserves v27 timer compatibility and v26 migration', () => { const current = createInitialGameState(); const { manualJobs: _manualJobs, ...v26 } = current; const migrated = migrateToCurrentSave({ format: SAVE_FORMAT, version: 26, savedAt: 1234, state: v26 }); expect(migrated.ok).toBe(true); if (!migrated.ok) return; expect(migrated.envelope.version).toBe(CURRENT_SAVE_VERSION); expect(migrated.envelope.state.manualJobs).toBeUndefined(); for (const elapsedMs of [MANUAL_JOB_INTERVAL_MS, MANUAL_JOB_INTERVAL_MS + 1]) expect(migrateToCurrentSave({ format: SAVE_FORMAT, version: CURRENT_SAVE_VERSION, savedAt: 1234, state: { ...migrated.envelope.state, manualJobs: { elapsedMs } } })).toEqual({ ok: false, error: 'invalid-state' }); });
  it('round-trips a pending special delay through JSON and CE1', () => { const risky = performRiskyDelivery(createInitialGameState()); expect(risky.ok).toBe(true); if (!risky.ok) return; const progressed = simulateGameElapsed(risky.state, 4000); expect(progressed.ok).toBe(true); if (!progressed.ok) return; const saved = serializeSave(progressed.state, 5000); expect(saved.ok).toBe(true); if (!saved.ok) return; const parsed = parseSave(saved.serialized); expect(parsed.ok && parsed.envelope.state.manualJobs?.elapsedMs).toBe(4000); const code = exportSaveCode(progressed.state, 5000); expect(code.ok).toBe(true); if (!code.ok) return; const imported = validateSaveCode(code.code); expect(imported.ok && imported.envelope.state.manualJobs?.elapsedMs).toBe(4000); });
  it('retains pending special cooldown through Rebirth', () => { const eligible = { ...rebirthState(), manualJobs: { elapsedMs: 2750 } }; const rebirth = performRebirth(eligible); expect(rebirth.ok).toBe(true); if (!rebirth.ok) return; expect(rebirth.state.manualJobs).toEqual({ elapsedMs: 2750 }); expect(performStarterJob(rebirth.state).ok).toBe(true); });
});
