export type Locale = 'en' | 'de';

export const DEFAULT_LOCALE: Locale = 'en';

const messages = {
  en: {
    skip: 'Skip to the profitable part',
    tagline: 'Own the night. Invoice nobody.',
    autosave: 'Autosave armed · bad decisions now legally documented.',
    returnEmpire: 'Back to Empire · your suspiciously important confirmation is waiting.',
    localProgress: 'Local progress · because the cloud asks too many questions',
    awayPrefix: 'Keep earning while conveniently unavailable for up to',
    footerGenre: 'Crime empire · allegedly',
    footerTagline: 'Start small. Scale irresponsibly.',
    settings: 'Settings',
    settingsTitle: 'Settings & questionable preferences',
    settingsIntro: 'Tune Solara City to your setup. These preferences stay on this device, far away from accountants and your actual progression.',
    language: 'Language',
    english: 'English',
    german: 'Deutsch',
    reducedMotion: 'Reduce motion',
    reducedMotionHelp: 'Cuts non-essential animation. Your empire remains morally flexible at full speed.',
    close: 'Close this totally legitimate menu',
    overviewLabel: 'OVERVIEW', overviewDescription: 'Your empire at a glance. Mostly assets. Definitely not evidence.',
    operationsLabel: 'OPERATIONS', operationsDescription: 'Move product, grow revenue and automate the parts your lawyer hates.',
    cityLabel: 'CITY', cityDescription: 'Own districts, manage Heat and keep the Crew expensive but useful.',
    collectionLabel: 'COLLECTION', collectionDescription: 'Collect questionable machinery. Enjoy completely legitimate bonuses.',
    empireLabel: 'EMPIRE', empireDescription: 'Turn temporary success into permanent tax problems.',
    primaryNavigation: 'Primary money-making departments',
    hudStatus: 'Current financial and legal situation',
    cash: 'Cash',
    playerLevel: 'Player Level',
    heat: 'Heat',
    empirePoints: 'Empire Points',
    cityEventActive: 'CITY EVENT ACTIVE',
    autoPaused: 'AUTO-UPGRADER ENABLED · SESSION PAUSED · lawyers relieved',
    autoActive: 'AUTO-UPGRADER ACTIVE · SPENDING ENABLED · accountant sweating',
    sessionPaused: 'SESSION PAUSED · criminal productivity temporarily zero',
  },
  de: {
    skip: 'Direkt zum profitablen Teil',
    tagline: 'Hol dir die Nacht. Stell bloß keine Rechnung aus.',
    autosave: 'Autosave läuft · deine fragwürdigen Entscheidungen sind jetzt aktenkundig.',
    returnEmpire: 'Zurück zum Imperium · deine verdächtig wichtige Bestätigung wartet.',
    localProgress: 'Lokaler Fortschritt · die Cloud stellt zu viele Fragen',
    awayPrefix: 'Verdiene unauffällig weiter für bis zu',
    footerGenre: 'Crime Empire · angeblich',
    footerTagline: 'Fang klein an. Eskalier wirtschaftlich.',
    settings: 'Einstellungen',
    settingsTitle: 'Einstellungen & fragwürdige Vorlieben',
    settingsIntro: 'Passe Solara City an dein Setup an. Diese Einstellungen bleiben auf diesem Gerät, weit weg von Buchhaltung und Spielfortschritt.',
    language: 'Sprache',
    english: 'English',
    german: 'Deutsch',
    reducedMotion: 'Bewegungen reduzieren',
    reducedMotionHelp: 'Reduziert unnötige Animationen. Dein Imperium bleibt trotzdem moralisch flexibel.',
    close: 'Dieses völlig seriöse Menü schließen',
    overviewLabel: 'ÜBERSICHT', overviewDescription: 'Dein Imperium auf einen Blick. Vermögen, Probleme und erstaunlich wenig Papierkram.',
    operationsLabel: 'OPERATIONEN', operationsDescription: 'Geld verdienen, Businesses hochziehen und die Arbeit automatisieren, die keiner freiwillig macht.',
    cityLabel: 'STADT', cityDescription: 'Bezirke kontrollieren, Heat im Zaum halten und die Crew teuer beschäftigen.',
    collectionLabel: 'SAMMLUNG', collectionDescription: 'Fragwürdige Maschinen sammeln. Völlig seriöse Boni kassieren.',
    empireLabel: 'IMPERIUM', empireDescription: 'Kurzfristigen Erfolg in langfristige Steuerprobleme verwandeln.',
    primaryNavigation: 'Primäre Abteilungen zur Geldvermehrung',
    hudStatus: 'Aktuelle finanzielle und rechtliche Gesamtlage',
    cash: 'Cash',
    playerLevel: 'Spielerlevel',
    heat: 'Heat',
    empirePoints: 'Empire Points',
    cityEventActive: 'STADTEVENT AKTIV',
    autoPaused: 'AUTO-UPGRADER AN · SESSION PAUSIERT · Anwalt entspannt',
    autoActive: 'AUTO-UPGRADER AKTIV · AUSGABEN FREIGEGEBEN · Buchhaltung schwitzt',
    sessionPaused: 'SESSION PAUSIERT · kriminelle Produktivität vorübergehend bei null',
  },
} as const;

export type MessageKey = keyof typeof messages.en;
export function translate(locale: Locale, key: MessageKey): string { return messages[locale][key]; }
export function localeTag(locale: Locale): string { return locale === 'de' ? 'de-DE' : 'en-US'; }
